simulator.http-logging.enabled=true
simulator.http-logging.include-request-body=true
simulator.http-logging.include-response-body=true
simulator.http-logging.max-payload-length=8000

logging.level.com.dt.digitaltwinsimulator=DEBUG
